apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "telegram-discord-bridge.fullname" . }}
  labels:
    {{- include "telegram-discord-bridge.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "telegram-discord-bridge.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "telegram-discord-bridge.selectorLabels" . | nindent 8 }}
    spec:
      strategy:
        type: Recreate
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "telegram-discord-bridge.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: data
              mountPath: /data
          env:
            - name: TELEGRAM_TOKEN
              value: {{ .Values.options.telegram_token }}
            - name: DISCORD_TOKEN
              value: {{ .Values.options.discord_token }}
            - name: CHANNELS
              value: {{ .Values.options.channels }}
            - name: MESSAGE_TTL
              value: {{ .Values.options.message_ttl }}
            - name: MESSAGE_DB
              value: /data/messages.db
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
