apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "telegram-discord-bridge.fullname" . }}
  labels:
    {{- include "telegram-discord-bridge.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.options.db_size }}