apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plane-so.fullname" . }}-proxy
  labels:
    {{- include "plane-so.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.proxy.enabled }}
  replicas: {{ .Values.replicaCount.proxy }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "plane-so.selectorLabels" . | nindent 6 }}
      plane.so/component: proxy
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "plane-so.selectorLabels" . | nindent 8 }}
        plane.so/component: proxy
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: DEBUG
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: DEBUG
            - name: DJANGO_SETTINGS_MODULE
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: DJANGO_SETTINGS_MODULE
            - name: NEXT_PUBLIC_ENABLE_OAUTH
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: NEXT_PUBLIC_ENABLE_OAUTH
            - name: NEXT_PUBLIC_DEPLOY_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: NEXT_PUBLIC_DEPLOY_URL
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: SENTRY_DSN
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: GITHUB_CLIENT_SECRET
            - name: DOCKERIZED
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: DOCKERIZED
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: PGHOST
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: PGDATABASE
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: POSTGRES_DB
            - name: PGDATA
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: PGDATA
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: DATABASE_URL
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: REDIS_PORT
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: REDIS_URL
            - name: EMAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: EMAIL_HOST
            - name: EMAIL_HOST_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: EMAIL_HOST_USER
            - name: EMAIL_HOST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: EMAIL_HOST_PASSWORD
            - name: EMAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: EMAIL_PORT
            - name: EMAIL_FROM
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: EMAIL_FROM
            - name: EMAIL_USE_TLS
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: EMAIL_USE_TLS
            - name: EMAIL_USE_SSL
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: EMAIL_USE_SSL
            - name: DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: DEFAULT_EMAIL
            - name: DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: DEFAULT_PASSWORD
            - name: OPENAI_API_BASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: OPENAI_API_BASE
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: OPENAI_API_KEY
            - name: GPT_ENGINE
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: GPT_ENGINE
            - name: ENABLE_SIGNUP
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: ENABLE_SIGNUP
            - name: ENABLE_EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: ENABLE_EMAIL_PASSWORD
            - name: ENABLE_MAGIC_LINK_LOGIN
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: ENABLE_MAGIC_LINK_LOGIN
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: SECRET_KEY
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: MINIO_ROOT_PASSWORD
            - name: FILE_SIZE_LIMIT
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: FILE_SIZE_LIMIT
            - name: GUNICORN_WORKERS
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: GUNICORN_WORKERS
            - name: USE_MINIO
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: USE_MINIO
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: AWS_REGION
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_S3_ENDPOINT_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: AWS_S3_ENDPOINT_URL
            - name: AWS_S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: AWS_S3_BUCKET_NAME
            - name: BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: BUCKET_NAME
            - name: API_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: API_HOST
            - name: WEB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: WEB_HOST
            - name: SPACE_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: SPACE_HOST
            - name: MINIO_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "plane-so.fullname" . }}-env
                  key: MINIO_HOST
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.proxy.repository }}:{{ .Values.image.proxy.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.proxy.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.proxy.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources.proxy | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
