{{- if .Values.autoscaling.space.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "plane-so.fullname" . }}-space
  labels:
    {{- include "plane-so.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "plane-so.fullname" . }}-space
  minReplicas: {{ .Values.autoscaling.space.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.space.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.space.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.space.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.space.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.space.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
