apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  metadata:
  name: {{ include "plane-so.fullname" . }}-minio
  labels:
    {{- include "plane-so.labels" . | nindent 4 }}
spec:
    accessModes: {{.Values.storage.minio.accessModes}}
    resources:
        requests:
          storage: {{ .Values.storage.minio.size }}
    storageClassName: {{ .Values.storage.minio.storageClass }}