apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plane-so.fullname" . }}-env
  labels:
    {{- include "plane-so.labels" . | nindent 4 }}
type: Opaque
stringData:
  # include all .values.env values
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  DOCKERIZED: "1"
  PGHOST: "{{ include "plane-so.fullname" . }}-postgres"
  PGDATA: "/var/lib/postgresql/data/pgdata"
  DATABASE_URL: "postgresql://{{ .Values.env.POSTGRES_USER }}:{{ .Values.env.POSTGRES_PASSWORD }}@{{ include "plane-so.fullname" . }}-postgres/{{ .Values.env.PGDATABASE }}"
  REDIS_HOST: "{{ include "plane-so.fullname" . }}-redis"
  REDIS_URL: "redis://${REDIS_HOST}:6379/"
  USE_MINIO: "1"
  AWS_REGION: ""
  AWS_ACCESS_KEY_ID: "{{ .Values.env.MINIO_ROOT_USER }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.env.MINIO_ROOT_PASSWORD }}"
  AWS_S3_ENDPOINT_URL: "http://{{ include "plane-so.fullname" . }}-minio:9000"
  AWS_S3_BUCKET_NAME: "uploads"
  BUCKET_NAME: "uploads"
