apiVersion: v1
kind: Service
metadata:
  name: {{ include "plane-so.fullname" . }}-redis
  labels:
    {{- include "plane-so.labels" . | nindent 4 }}
    plane.so/component: redis
spec:
  type: {{ .Values.service.redis.type }}
  ports:
    - port: {{ .Values.service.redis.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "plane-so.selectorLabels" . | nindent 4 }}
    plane.so/component: redis
