apiVersion: v1
kind: Service
metadata:
  name: {{ include "plane-so.fullname" . }}-beat-worker
  labels:
    {{- include "plane-so.labels" . | nindent 4 }}
    plane.so/component: beat-worker
spec:
  type: {{ .Values.service.beatWorker.type }}
  ports:
    - port: {{ .Values.service.beatWorker.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "plane-so.selectorLabels" . | nindent 4 }}
    plane.so/component: beat-worker
