apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "gitlab-aio.fullname" . }}-updater
  labels:
    {{- include "gitlab-aio.labels" . | nindent 4 }}
spec:
  schedule: 20 2 * * *
  concurrencyPolicy: Forbid
  suspend: false
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - name: kubectl
              image: lwolf/helm-kubectl-docker:v1.21.1-v3.6.0
              command:
                - kubectl
              args:
                - delete
                - pods/{{ include "gitlab-aio.fullname" . }}-0
                - '-n'
                - {{.Release.Namespace}}
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: IfNotPresent
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          serviceAccountName: {{ include "gitlab-aio.serviceAccountName" . }}
          serviceAccount: {{ include "gitlab-aio.serviceAccountName" . }}
          securityContext: {}
          schedulerName: default-scheduler
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
