apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "gitlab-aio.fullname" . }}-updater
  labels:
    {{- include "gitlab-aio.labels" . | nindent 4 }}
rules:
    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["delete"]
      resourceNames: ["{{ include "gitlab-aio.fullname" . }}-0"]