apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "gitlab-aio.fullname" . }}-updater
  labels:
    {{- include "gitlab-aio.labels" . | nindent 4 }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: {{ include "gitlab-aio.fullname" . }}-updater
subjects:
    - kind: ServiceAccount
      name: {{ include "gitlab-aio.serviceAccountName" . }}