apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitlab-aio.fullname" . }}
  labels:
    {{- include "gitlab-aio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.web.type }}
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: {{ .Values.services.web.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.services.web.httpsPort }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "gitlab-aio.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitlab-aio.fullname" . }}-ssh
  labels:
    {{- include "gitlab-aio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.ssh.type }}
  ports:
    - port: {{ .Values.services.ssh.port }}
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    {{- include "gitlab-aio.selectorLabels" . | nindent 4 }}